### ISSUE TITLE
Which TypeSpecifier should I use for c++-class?

### ISSUE THREAD

**Issue by junjihashimoto** [fpco/inline-c-cpp#1]
Hi,

I write a example of inline-c-cpp like https://github.com/junjihashimoto/inline-c-cpp-test/blob/master/tests.hs.
I use C.TypeName for c++-class-name in the example.

I should add TypeSpecifier for c++-class
in https://github.com/fpco/inline-c/blob/master/src/Language/C/Types.hs#L85 ?

Do you think this use case is correct?

**Comment by bitonic** [comment]
We currently do not support parsing of C++ types.  It so happens that `TypeSpecifier` will work for your purpose (since a class name is very similar to a `typedef` when parsing), and currently there is no better way of doing this.

In the future we want better support for C++, and this will probably mean writing a separate parser for C++ types.

**Comment by junjihashimoto** [comment]
I am looking forward to a parser for C++ types( class and template ).

**Comment by mboes** [comment]
@junjihashimoto pull requests welcome. :)
